site_name: Портал KNHcloud
site_url: http://knhcloud

theme:
  name: material
  language: ru
  logo: assets/luk-logo.jpg
  favicon: assets/luk-logo.jpg
  features:
    - navigation.footer
  palette:
    primary: red

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

extra:
  consent:
    title: Согласие на обработку персональных данных
    description: >-
      Мы используем cookies для улучшения работы сайта, анализа трафика и персонализации.
      Используя сайт или кликая на кнопку "Принять", Вы соглашаетесь с нашей политикой использования cookies.
    actions:
      - accept
      - manage

plugins:
  - search
  - table-reader

copyright:
  Copyright &copy; 2025 KNHCloud
